- name: Instalar dependências do Docker
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common"]
    state: present
    update_cache: yes

- name: Adicionar chave GPG do Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adicionar repositório do Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Instalar Docker e Docker Compose
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-compose-plugin"]
    state: present
    update_cache: yes

- name: Criar rede externa "proxy"
  docker_network:
    name: portfolio_net
    driver: bridge
    state: present
