- name: Criar diretório do Homer
  file:
    path: /opt/homer
    state: directory
    mode: '0755'

- name: Copiar docker-compose do Homer
  copy:
    src: ../../apps/homer/docker-compose.yml
    dest: /opt/homer/docker-compose.yml
    mode: '0644'

- name: Subir containers do Homer
  shell: docker-compose up -d
  args:
    chdir: /opt/homer
