version: '3.8'
services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - portfolio_net
networks:
  portfolio_net:
    external: true
