- name: Criar diretório do app
  file:
    path: "{{ app_dest }}"
    state: directory
    mode: '0755'

- name: Copiar arquivos do app ignorando exclusões
  ansible.posix.synchronize:
    src: "{{ app_src }}"
    dest: "{{ app_dest }}"
    rsync_opts: "{{ app_excludes | default([]) | map('regex_replace', '^', '--exclude=') | list }}"
    use_ssh_args: true
    mode: push

- name: Subir containers do app
  shell: docker-compose up -d
  args:
    chdir: "{{ app_dest }}"
